version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-sphinx-theme"
    commit-message:
      prefix: "BUILD(pip)"
