version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies:pyproject"
    commit-message:
      prefix: "build"
    groups:
      tests:
        patterns:
          - "pytest*"
      doc:
        patterns:
          - "*sphinx*"
