[project]
name = "DummyRepo"

dependencies = [
    "tomli; python_version < '3.11'",
    "tomli-w",
]

[project.optional-dependencies]
doc = [
    "ansys-sphinx-theme>=1.0.0,<1.5",
    "numpydoc>=1.5.0,<1.8",
]
